### PR TITLE
Update augeasproviders_core version

### PR DESCRIPTION
**Pull request by sazzle2611**

### CODE REVIEW

**Review by smortex — APPROVED** [review]
Looks good.

**Comment by sazzle2611** [comment]
@smortex  thank you :)

**Comment by jhoblitt** [comment]
I'm hesitant to merge this without working CI but obviously it is needed...

**Review by jhoblitt — APPROVED** [review]
This is working for me on baremetal.

**Comment by jhoblitt** [comment]
I'm going to merge this since my prod env hasn't blown up with it.

**Pull request merged**
