### PR TITLE
Release 5.1.2

### PR DESCRIPTION
**Pull request by vchepkov**
Release 5.1.2

### CODE REVIEW

**Review by kenyon — CHANGES_REQUESTED** [review]
The `-rc0` needs to be removed from the version in `metadata.json` for the changelog to be generated correctly.

I wonder why that `simp-2.3.1` tag appeared. Maybe should be deleted?

**Comment by vchepkov** [comment]
Hmm, I used documentation https://voxpupuli.org/docs/releasing_version/

`CHANGELOG_GITHUB_TOKEN='mytoken' bundle exec rake release:prepare`

I assumed that will be removed during actual release, I will remove the suffic

**Comment by vchepkov** [comment]
I don't see that tag?

$ git tag
2.0.0
2.0.1
2.1.0
2.2.0
2.3.0
2.4.0
3.0.0
3.0.1
3.1.0
3.2.0
v4.0.0
v5.0.0
v5.0.1
v5.1.0
v5.1.1

**Review by kenyon — CHANGES_REQUESTED** [review]
That tag is here: https://github.com/voxpupuli/puppet-augeasproviders_grub/releases/tag/simp-2.3.1

🤷 

I think you need to regenerate the changelog now that you've set the version. It shouldn't say `Unreleased`, it should be `v5.1.2`. Here's an example: https://github.com/voxpupuli/puppet-python/pull/697

**Comment by vchepkov** [comment]
I just committed my section of the change and removed others manually

**Review by kenyon — APPROVED** [review]

**Comment by kenyon** [comment]
I deleted that simp-2.3.1 tag from the repo so that hopefully it doesn't show up in the next changelog.

**Pull request merged**
